### ISSUE TITLE
Mistake in the Cryptoguard rule mapping

### ISSUE THREAD

**Issue by panoob** [xinjin95/IoTSpotter#2]
I noticed a mistake made in the paper. In table 4, the rule number mapping puts Rule 2 and 10 together. Same mapping is also public in the [repo](https://github.com/Secure-Platforms-Lab-W-M/IoTSpotter/blob/main/data/cryptoguard_correction/cryptoguard_rules_mapping.csv). 

But according to the Cryptoguard [source code](https://github.com/CryptoGuardOSS/cryptoguard/blob/master/src/main/java/rule/ConstantKeyFinder.java), Rule 2 in the paper should be mapped to the Rule 3 in the tool. Hope this can help you to avoid misunderstanding.

**Comment by xinjin95** [comment]
Hi @panoob, 

Thanks for your interest in our IoTSpotter paper! 

We'd like to clarify that we didn't make mistakes on rule ID. We calculated the number of violations on each rule ID based on Cryptoguard's execution report.  For example, the reported violation of rule 2 was:

```plaintext
=======================================
***Violated Rule 2: Found broken hash functions ***Constants: ["MD5", "MD5", "MD5", "MD5", "SHA-1", "SHA-1", "MD5", "MD5", "MD5", "MD5", "SHA1", "MD5", "MD5", "SHA-1", "SHA-1", "MD5", "MD5", "SHA-1", "SHA-1", "MD5", "SHA-1", "SHA-1", "SHA-1", "MD5", "MD5", "MD5", "SHA1", "MD5", "MD5", "SHA1"]
```

By reading the Cryptoguard paper, we found the description for rule 16 is "Broken Hash" and rule 2's description is "Predictable Password for PBE". This motivated us to create such a correction in our [repo](https://github.com/Secure-Platforms-Lab-W-M/IoTSpotter/blob/main/data/cryptoguard_correction/cryptoguard_rules_mapping.csv).

While we calculated violation numbers in an end-to-end way, we believe it's not a mistake. 

The difference between the code you referred to and our execution reports may be caused by the different versions of Cryptoguard used by you and us.

BTW, thanks for your attention!

**Comment by panoob** [comment]
![image](https://user-images.githubusercontent.com/114906886/216752296-89c42953-0434-4f40-8b0c-b6c29453c70c.png)

**Comment by panoob** [comment]
I mean Rule 2 in the paper "Predictable/constant passwords for PBE" are actually mapped to the Rule 3 in the tool "Used constant keys in code". 

The code I shared is the source code of Cryptoguard for reporting Rule 3. As below picture shows, this implementation set the slicing criterion for PBE "password" parameters. 
![image](https://user-images.githubusercontent.com/114906886/216752443-5f0a56a1-be48-4d01-96d3-05e544290c44.png)

You can refer to this [Java official documents](https://docs.oracle.com/javase/8/docs/api/javax/crypto/spec/PBEKeySpec.html). This points out the 0th parameter is for password.
![image](https://user-images.githubusercontent.com/114906886/216752539-1bc89b34-45e8-441f-a9e3-b6783e7abacb.png)

I understand the original tool made this confusion between paper number and tool number. I am pointing out this for unnecessary misleading of future readers. Hope my explanation help.

**Comment by xinjin95** [comment]
Good to know this. Thanks for your information.
